name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'openshwprojects/OpenLN882H'
          submodules: 'recursive'
          fetch-depth: 0
      
      - name: Fix Submodules
        run: |
          # Эта команда принудительно скачивает код OpenBeken
          git submodule update --init --recursive
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Build
        run: |
          pip install pyelftools
          # Создаем папку вручную, чтобы скрипт не ругался
          mkdir -p project/wifi_mcu_basic_example/output/
          python3 start_build.py rebuild
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: project/wifi_mcu_basic_example/output/
