name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Enable TM1637
        run: |
          # Эта магия включает драйвер прямо в коде перед сборкой
          find . -name "new_common.h" -exec sed -i 's/#define ENABLE_DRIVER_TM1637 0/#define ENABLE_DRIVER_TM1637 1/g' {} +
          echo "#define ENABLE_DRIVER_TM1637 1" >> src/new_common.h
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build
        run: |
          pip install pyelftools
          python3 start_build.py rebuild
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Custom_OpenLN882H_TM1637
          path: project/wifi_mcu_basic_example/output/
